Repository nrkno/core-components, pull requests merged in 2019-05, with the labels that each got.

#235 custom elements
  bin/index.js
  package-lock.json
  package.json
  packages/core-datepicker/readme.md
  packages/core-dialog/readme.md
  packages/core-input/readme.md
  packages/core-progress/readme.md
  packages/core-scroll/core-scroll.js
  packages/core-scroll/readme.md
  packages/core-tabs/readme.md
  packages/core-toggle/readme.md
  packages/index.html
  packages/readme.md
  readme.md
  rollup.config.js
Labels: enhancement

#242 Feature/core suggest
  packages/core-datepicker/core-datepicker.js
  packages/core-dialog/core-dialog.js
  packages/core-input/core-input.jsx
  packages/core-progress/core-progress.js
  packages/core-suggest/core-suggest.js
  packages/core-suggest/core-suggest.jsx
  packages/core-suggest/core-suggest.test.js
  packages/core-suggest/package-lock.json
  packages/core-suggest/package.json
  packages/core-suggest/readme.md
  packages/core-tabs/core-tabs.js
  packages/core-toggle/core-toggle.js
  packages/index.html
  packages/utils.js
Labels: enhancement

#249 fix react event handling bug
  packages/utils.js
Labels: bug

#250 docs: write about suggest markup and list attr
  packages/core-suggest/readme.md
  packages/core-toggle/readme.md
Labels: documentation

#253 core-progress: set default type on init
  packages/core-progress/core-progress.js
Labels: bug

#258 use external dep for elem2react
  package-lock.json
  package.json
  packages/core-datepicker/core-datepicker.jsx
  packages/core-dialog/core-dialog.jsx
  packages/core-progress/core-progress.jsx
  packages/core-scroll/core-scroll.jsx
  packages/core-suggest/core-suggest.jsx
  packages/core-tabs/core-tabs.jsx
  packages/core-toggle/core-toggle.jsx
  packages/index.html
  packages/utils.js
  packages/utils.test.js
  rollup.config.js
Labels: enhancement

#259 Fix backdrop creation on init
  packages/core-dialog/core-dialog.js
  packages/core-progress/readme.md
Labels: bug
