Repository nrkno/core-components, pull requests merged in 2019-09, with the labels that each got.

#336 Toggle and focus refinements
  packages/core-dialog/core-dialog.js
Labels: bug, enhancement

#326 rewrite tests with protractor
  .github/workflows/main.yml
  .gitignore
  .travis.yml
  bin/test.js
  package-lock.json
  package.json
  packages/core-datepicker/core-datepicker.test.js
  packages/core-dialog/core-dialog.test.js
  packages/core-progress/core-progress.test.js
  packages/core-progress/readme.md
  packages/core-scroll/core-scroll.test.js
  packages/core-suggest/core-suggest.js
  packages/core-suggest/core-suggest.test.js
  packages/core-suggest/readme.md
  packages/core-tabs/core-tabs.test.js
  packages/core-tabs/readme.md
  packages/core-toggle/core-toggle.test.js
  packages/test-ie11.html
  readme.md
Labels: enhancement

#349 Rename `CoreScoll` => `CoreScroll`
  packages/core-scroll/core-scroll.js
  packages/core-scroll/readme.md
Labels: bug
