Repository nrkno/core-components, pull requests merged in 2021-08, with the labels that each got.

#615 Replace rollup-plugin -uglify with -terser
  package-lock.json
  package.json
  rollup.config.js
Labels: dependencies

#617 feature: Support data for attribute
  packages/core-datepicker/core-datepicker.js
  packages/core-datepicker/readme.md
  packages/core-dialog/core-dialog.js
  packages/core-dialog/core-dialog.test.js
  packages/core-dialog/readme.md
  packages/core-progress/readme.md
  packages/core-scroll/core-scroll.js
  packages/core-scroll/core-scroll.test.js
  packages/core-scroll/readme.md
  packages/core-suggest/readme.md
  packages/core-tabs/core-tabs.js
  packages/core-tabs/core-tabs.test.js
  packages/core-tabs/readme.md
  packages/core-toggle/core-toggle.js
  packages/core-toggle/core-toggle.test.js
  packages/core-toggle/readme.md
  packages/migration.md
  packages/readme.md
Labels: enhancement

#618 fix: Reset internals on unmount and abort execution accordingly
  packages/core-datepicker/core-datepicker.js
  packages/core-scroll/core-scroll.js
  packages/core-suggest/core-suggest.js
  packages/core-tabs/core-tabs.js
Labels: enhancement

#512 core-tabs: Fix docs and zero-index detection
  packages/core-tabs/core-tabs.js
  packages/core-tabs/core-tabs.test.js
  packages/core-tabs/readme.md
Labels: enhancement

#620 Highlight optional
  packages/core-suggest/core-suggest.js
  packages/core-suggest/core-suggest.test.js
  packages/core-suggest/readme.md
  packages/utils.js
Labels: enhancement

#621 core-scroll: Remove use of will-change: scroll-position
  packages/core-scroll/core-scroll.js
Labels: enhancement

#623 Core dialog allow focusing links
  packages/core-dialog/core-dialog.js
  packages/core-dialog/readme.md
Labels: bug

#622 From browserstack to cbt
  bin/test.js
  package-lock.json
  package.json
  packages/core-suggest/core-suggest.test.js
  readme.md
Labels: enhancement
